# Generated by Django 6.0.4 on 2026-04-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prize',
            new_name='price',
        ),
    ]
